# Matrix  in python

### Creating Matrix in python 

In [1]:
import numpy as np

In [2]:
matrix  = np.array([[4,5,6],[3,2,1],[7,8,9]])
print(matrix)

[[4 5 6]
 [3 2 1]
 [7 8 9]]


In [3]:
matrix.shape

(3, 3)

Creating Random matrix

In [4]:
r_m = np.random.randint(1,10,[3,3])
print(r_m)

[[4 5 5]
 [1 6 9]
 [5 9 4]]


In [5]:
# matrix with ones 
m = np.ones((3,3))
print(m)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
#Null Matrix
print(np.zeros((4,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
print(np.eye(3,3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Transpose of matrix

In [8]:
a = np.random.randint(0,100,(4,4))
a_t = np.transpose(a)
print(a)
print()
print(a_t)

[[15  3 22 23]
 [54 56 81 89]
 [84 86 85 20]
 [84 97 27 25]]

[[15 54 84 84]
 [ 3 56 86 97]
 [22 81 85 27]
 [23 89 20 25]]


## Matrix Operation 

In [23]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(0,10,(3,3))
print(a)
print(b)


[[9 4 5]
 [5 8 4]
 [0 1 6]]
[[7 2 4]
 [0 3 5]
 [6 1 3]]


In [24]:
a.shape, b.shape

((3, 3), (3, 3))

Addition 

In [25]:
c = a + b
print(c)

[[16  6  9]
 [ 5 11  9]
 [ 6  2  9]]


Subtraction

In [26]:
d = a-b 
print(d)

[[ 2  2  1]
 [ 5  5 -1]
 [-6  0  3]]


Multiply with scaler 

In [27]:
a2 = 2*a
print(a2)

[[18  8 10]
 [10 16  8]
 [ 0  2 12]]


MULTIPLICATION WITH OTHER MATRIX

In [28]:
m = np.dot(a,b)
print(m)

[[93 35 71]
 [59 38 72]
 [36  9 23]]
